Fix the off by 0.5 problem.
This made the function calcp too complex for the poor swift compiler so I've
split it into to - gen(n) which generates an array and calcp(n) which does the
integration.

We have to split this into two functions otherwise the Swift 3.x compiler
complains:

error: expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions

Looking at stackoverflow this is a... feature of the compiler:
   http://stackoverflow.com/questions/29707622/bizarre-swift-compiler-error-expression-too-complex-on-a-string-concatenation